data:
  root_dir: "../../data"                        # główny katalog danych
  train: "train"                                # podkatalog treningowy
  val: "val"                                    # podkatalog walidacyjny
  test: "test"                                  # podkatalog testowy
  batch_size: 32
  image_size: 224                               # rozmiar wejściowy dla modelu

model:
  base_model: "resnet50"                        # image_size: 224
  num_classes: 2
  pretrained: true
  freeze_encoder: false
  dropout_rate: 0.5
  weight_decay: 0.01

######################### ALTERNATYWNE MODELE ###########################
#                                                                       #
#  base_model: "convnext_large"                 # image_size: 384       #
#  base_model: "vit_h_14"                       # image_size: 384       #
#  base_model: "resnet50"                        # image_size: 224      #
#  base_model: "regnety_032"                    # image_size: 384       #
#               "efficientnet_v2_l"               # image_size: 480                                                        #
######################### ALTERNATYWNE MODELE ###########################

training:
  epochs: 150
  learning_rate: 0.00001
  device: "auto"
  checkpoint_dir: "../../checkpoints"           # miejsce zapisu modelu

prediction:
  model_path: "checkpoints/resnet50_epoch_42_acc_83.17.pth"
  image_path: "data/test/Głębia_Gdańska_0013_otsu_OBRYS_1.jpg"
  results_dir: "results/gradcam"
  show_visualization: true
  save_results: true                            # czy wyświetlać wykresy matplotlib

prediction_modes:
  mode: "single"                                # "single" lub "batch"
  batch:
    num_images: 4                               # liczba obrazów do wyświetlenia w trybie batch
    min_confidence: 70                          # minimalna pewność predykcji dla obrazów w trybie batch
  navigation:
    image_dir: "data/test"                      # katalog z obrazami do nawigacji w trybie single


visualization:
  methods: ['gradcam', 'gradcam++', 'guided_backprop']
  display_mode: 'matrix'
  matrix_cols: 3
  save_individual: False
  target_layer: "base.layer4.2.conv3"           #resnet50:"base.layer4.2.conv3"; efficientnet:"base.features.8.0"
  colormap: "jet"
  alpha: 0.5
