# Global settings
mode: "multitask"            # "single" or "multitask"
model_name: "resnet50"    # Choose from: resnet50, convnext_large, vit_h_14, efficientnet_v2_l, regnet_y_32gf

# Data settings
data:
  metadata_file: "data_loader/AnalysisWithOtolithPhoto_with_sets.xlsx"
  root_dir: "data"
  train: "train"
  val: "val"
  test: "test"
  batch_size: 32
  active_populations: [1, 2]
  augment_threshold: 0.7

# Model generic settings
base_model:
  pretrained: true
  freeze_encoder: false
  dropout_rate: 0.5
  weight_decay: 0.01

multitask_model:
  classifier_head:
    type: "linear"
    dropout_rate: 0.5
  regression_head:
    type: "mlp"
    hidden_dim: 128
    dropout_rate: 0.3
  loss_weighting:
    method: "uncertainty"       # "static", "uncertainty", "gradnorm", "none"
    static:
      classification: 1.0
      age: 0.3
  log_loss_components: true
  metrics_weights:
    alpha: 0.34
    beta: 0.33
    gamma: 0.33

# Augmentation settings
augmentation:
  rotation: 30
  crop_scale: [0.8, 1.0]
  hflip_prob: 0.5
  vflip_prob: 0.5
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.05
  affine_degrees: 15
  affine_translate: [0.1, 0.1]
  affine_scale: [0.9, 1.1]
  affine_shear: 10
  gaussian_blur_kernel: 3

# Training settings
training:
  loss_type:
    - standard_ce
    #- class_balanced_focal
    #- focal_tversky
    #- ghm
    #- seesaw
    #- asymmetric_focal
    #- sample_weighted_ce
    #- weighted_age_ce
    # - focal_loss_ageboost
    #- ldam
  stop_after_one_epoch: true
  epochs: 150
  learning_rate: 0.00001
  device: "auto"
  early_stopping_patience: 5
  checkpoint_dir: "checkpoints"

# Visualization settings
visualization:
  methods: ['gradcam', 'gradcam++', 'guided_backprop']
  display_mode: 'matrix'
  matrix_cols: 3
  save_individual: False
  colormap: "jet"
  alpha: 0.5
  generate_heatmaps_in_report: true
  n_heatmap_cases: 3