data:
  root_dir: "data"
  train: "train"
  val: "val"
  batch_size: 32
  image_size: 224

model:
  base_model: "resnet50"
  num_classes: 2
  pretrained: True
  freeze_encoder: False         # Set True for transfer learning
  dropout_rate: 0.5             # współczynnik dropout (np. 0.5 lub 0.3, albo 0.0 żeby wyłączyć)

training:
  epochs: 50
  learning_rate: 0.001
  device: "auto"
  checkpoint_dir: "../../checkpoints"
